import { buildMesh as buildMeshCore, orientedTriangles as orientedTrianglesCore, validateMesh as validateMeshCore } from './mesh-core.mjs';

const parts = [
  { id: 'socket', name: 'Transtibial socket', kind: 'Interface shell', category: 'Lower limb', meta: 'KIT / PE-101', thumb: 'socket', desc: 'Residual-limb interface study', length: 420, thickness: 4.5, radius: 8, color: '#d27650', range: [280, 520] },
  { id: 'cranial', name: 'Cranial contour plate', kind: 'Contour study', category: 'Craniofacial', meta: 'KIT / CF-204', thumb: 'cranial', desc: 'Cranial defect contour study', length: 142, thickness: 3.2, radius: 5, color: '#9fb9dc', range: [80, 220] },
  { id: 'finger', name: 'Phalanx / joint study', kind: 'Joint segment', category: 'Upper limb', meta: 'KIT / UL-031', thumb: 'finger', desc: 'Articulation envelope study', length: 52, thickness: 2.6, radius: 2.5, color: '#95d3a0', range: [25, 80] },
  { id: 'orbit', name: 'Orbital rim study', kind: 'Rim support', category: 'Craniofacial', meta: 'KIT / CF-118', thumb: 'orbit', desc: 'Bilateral contour study', length: 76, thickness: 2.8, radius: 4, color: '#d6ad74', range: [35, 120] },
  { id: 'blank', name: 'Custom volume blank', kind: 'Neutral starter', category: 'All', meta: 'TEMPLATE / 001', thumb: 'blank', desc: 'Underspecified study volume', length: 100, thickness: 4, radius: 6, color: '#b6c2bc', range: [40, 260] },
];

const catalogFallback = { sources: [
  { id: 'slicer', name: '3D Slicer', kind: 'segmentation workstation', url: 'https://www.slicer.org/', license: 'Open source; verify components', supports: ['DICOM', 'labelmaps', 'closed surfaces'], role: 'Author and review segmentations' },
  { id: 'dicom', name: 'DICOM / DICOMweb', kind: 'clinical data standard', url: 'https://dicom.nema.org/medical/dicom/current/output/chtml/part18/ps3.18.html', license: 'Standards publication', supports: ['study provenance', 'frame of reference', 'surface segmentation'], role: 'Preserve source identity and coordinates' },
  { id: 'open-anatomy', name: 'Open Anatomy Project', kind: 'open anatomy atlas', url: 'https://www.openanatomy.org/', license: 'Per-atlas terms', supports: ['MRI', 'CT', 'named structures'], role: 'Anatomical context, not device templates' },
  { id: 'z-anatomy', name: 'Z-Anatomy / BodyParts3D', kind: 'Blender anatomy reference', url: 'https://github.com/Z-Anatomy/Models-of-human-anatomy', license: 'CC BY-SA; attribution required', supports: ['Blender', 'anatomical meshes', 'labels'], role: 'Blender-native semantic reference' },
  { id: 'ohif', name: 'OHIF + Cornerstone3D', kind: 'web imaging viewer', url: 'https://docs.ohif.org/', license: 'MIT for OHIF; check dependencies', supports: ['DICOMweb', 'MPR', 'labelmaps', 'measurement'], role: 'Reference study viewer' },
  { id: 'monai-label', name: 'MONAI Label', kind: 'human-in-the-loop ML', url: 'https://docs.monai.io/projects/label/en/latest/', license: 'Open source; model terms vary', supports: ['interactive labeling', 'active learning'], role: 'Research-only assisted annotation' },
  { id: 'itk', name: 'ITK / SimpleITK', kind: 'image and mesh processing', url: 'https://docs.itk.org/', license: 'Apache 2.0; verify modules', supports: ['registration', 'image processing', 'mesh IO'], role: 'Image-to-surface and transform reference' },
  { id: 'vtk', name: 'VTK', kind: 'visualization and geometry toolkit', url: 'https://vtk.org/', license: 'BSD-style; verify dependencies', supports: ['polydata', 'volume rendering', 'mesh filters'], role: 'Review visualization and mesh operations' },
  { id: 'open3d', name: 'Open3D', kind: '3D data processing', url: 'https://www.open3d.org/', license: 'MIT; verify bundled components', supports: ['point clouds', 'meshes', 'registration'], role: 'Research registration and inspection reference' },
  { id: 'cgal', name: 'CGAL', kind: 'computational geometry', url: 'https://www.cgal.org/', license: 'GPL/LGPL components; review choice', supports: ['mesh generation', 'exact predicates', 'repair'], role: 'Candidate robust geometry kernel' },
  { id: 'opencascade', name: 'Open CASCADE Technology', kind: 'CAD kernel', url: 'https://dev.opencascade.org/', license: 'LGPL with exception; verify obligations', supports: ['STEP', 'BREP', 'booleans'], role: 'Candidate CAD/milling handoff kernel' },
  { id: 'gmsh', name: 'Gmsh', kind: 'finite-element mesh generator', url: 'https://gmsh.info/', license: 'GPL; verify plugins', supports: ['CAD import', 'remeshing', 'tetrahedralization'], role: 'Research volumetric meshing reference' },
  { id: 'slicercmf', name: 'SlicerCMF', kind: 'cranio-maxillofacial extension', url: 'https://github.com/DCBIA-OrthoLab/SlicerCMF', license: 'Review repository and extension terms', supports: ['craniofacial registration', 'dental imaging'], role: 'Craniofacial research workflow reference' },
  { id: 'tcia', name: 'TCIA / NIH 3D', kind: 'research reference data', url: 'https://www.cancerimagingarchive.net/', license: 'Collection-specific terms', supports: ['de-identified studies', '3D model references'], role: 'Reproducible test fixtures' },
] };

const state = {
  selectedPart: 'socket', category: 'All', query: '', tool: 'select', view: 'solid', grid: true,
  yaw: -0.32, pitch: -0.1, zoom: 1, dragging: false, lastX: 0, lastY: 0,
  length: 420, thickness: 4.5, radius: 8, symmetry: true, plane: true,
  material: 'Nylon 12', process: 'FDM / SLS', layer: '0.10 mm', validationRun: false,
  source: { kind: 'template', name: '', status: 'template-only', files: [] },
  history: [], historyIndex: -1, catalog: catalogFallback,
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const canvas = $('#modelCanvas');
const ctx = canvas.getContext('2d');
let toastTimer;

function currentPart() { return parts.find((part) => part.id === state.selectedPart) || parts[0]; }
function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('is-visible'); clearTimeout(toastTimer); toastTimer = setTimeout(() => element.classList.remove('is-visible'), 2600); }
function sourceLabel() { return state.source.kind === 'imported' ? 'unverified local source' : 'template only'; }
function snapshot() { return JSON.stringify({ selectedPart: state.selectedPart, length: state.length, thickness: state.thickness, radius: state.radius, symmetry: state.symmetry, plane: state.plane, material: state.material, process: state.process, layer: state.layer, source: state.source }); }
function commitHistory() { const item = snapshot(); if (state.history[state.historyIndex] === item) return; state.history = state.history.slice(0, state.historyIndex + 1); state.history.push(item); state.historyIndex = state.history.length - 1; }

function renderLibrary() {
  const filtered = parts.filter((part) => { const matchesCategory = state.category === 'All' || part.category === state.category; const haystack = `${part.name} ${part.kind} ${part.category}`.toLowerCase(); return matchesCategory && haystack.includes(state.query.toLowerCase()); });
  $('#libraryList').innerHTML = filtered.map((part) => `<button class="library-card ${part.id === state.selectedPart ? 'is-selected' : ''}" data-part="${part.id}"><span class="part-thumbnail ${part.thumb}" style="--part-accent:${part.color}"></span><span class="library-card-copy"><strong>${part.name}</strong><small>${part.kind}</small></span><span class="library-card-meta">${part.meta}</span></button>`).join('') || '<div class="empty-library">No starter geometry matches this search.</div>';
  $$('.library-card').forEach((button) => button.addEventListener('click', () => selectPart(button.dataset.part)));
}

function selectPart(id) { const part = parts.find((item) => item.id === id) || parts[0]; state.selectedPart = part.id; state.length = part.length; state.thickness = part.thickness; state.radius = part.radius; state.validationRun = false; commitHistory(); renderLibrary(); renderProperties(); resizeCanvas(); toast(`${part.name} loaded as a template study`); }

function renderStudySource() {
  const imported = state.source.kind === 'imported';
  $('#studyName').textContent = imported ? 'Unverified local reference' : 'Template geometry study'; $('#studyStatusPill').textContent = imported ? 'source queued' : 'template only'; $('#studyStatusPill').classList.toggle('is-imported', imported);
  $('#studyCardTitle').textContent = imported ? state.source.name : 'No source loaded'; $('#studyCardDetail').textContent = imported ? `${state.source.files.length} file${state.source.files.length === 1 ? '' : 's'} queued · parsing not implemented` : 'Template geometry only · no anatomy claim'; $('#studyCardAction').textContent = imported ? 'Replace source file' : 'Add a reference file'; $('#studyCard').classList.toggle('has-source', imported);
  $('#intentCount').textContent = '00'; $('#intentEmpty').textContent = imported ? 'Source is queued, but no reviewed segmentation or design intent is linked.' : 'No anatomy-linked intent yet. Import a study or stay in template mode.'; $('#workflowStatusIcon').textContent = imported ? '!' : '•'; $('#workflowStatusIcon').classList.toggle('is-neutral', !imported); $('#workflowStatusIcon').classList.toggle('is-review', imported); $('#viewportBanner').textContent = imported ? 'UNVERIFIED SOURCE · SEGMENTATION NOT LINKED · PREVIEW EXPORT ONLY' : 'TEMPLATE STUDY · NO SOURCE ATTACHED · PREVIEW EXPORT ONLY';
}

function renderProperties() {
  const part = currentPart(); $('#propertyTitle').textContent = part.name; $('#objectName').textContent = part.kind; $('#objectDescriptor').textContent = part.desc;
  $('#lengthSlider').min = part.range[0]; $('#lengthSlider').max = part.range[1]; $('#lengthSlider').value = Math.max(part.range[0], Math.min(part.range[1], state.length)); $('#thicknessSlider').value = state.thickness; $('#radiusSlider').value = state.radius;
  $('#lengthOutput').textContent = `${Number(state.length).toFixed(1)} mm`; $('#thicknessOutput').textContent = `${Number(state.thickness).toFixed(1)} mm`; $('#radiusOutput').textContent = `${Number(state.radius).toFixed(1)} mm`; $('#measureValue').textContent = Number(state.length).toFixed(1);
  $('#materialSelect').value = state.material; $('#processSelect').value = state.process; $('#layerSelect').value = state.layer; $('#symmetryToggle').classList.toggle('is-on', state.symmetry); $('#symmetryToggle').setAttribute('aria-checked', state.symmetry); $('#planeToggle').classList.toggle('is-on', state.plane); $('#planeToggle').setAttribute('aria-checked', state.plane);
  renderStudySource(); renderValidation(); renderWorkflow();
}

function buildMesh() { return buildMeshCore(state.selectedPart, state.length, state.thickness, state.radius); }

function project([x, y, z], scale, centerX, centerY) { const cy = Math.cos(state.yaw), sy = Math.sin(state.yaw), cp = Math.cos(state.pitch), sp = Math.sin(state.pitch), x1 = x * cy - z * sy, z1 = x * sy + z * cy, y1 = y * cp - z1 * sp, z2 = y * sp + z1 * cp, perspective = 1 + z2 / 1200; return { x: centerX + x1 * scale * perspective, y: centerY - y1 * scale * perspective, depth: z2 }; }
function drawGrid(width, height) { if (!state.grid) return; ctx.save(); ctx.globalAlpha = .22; ctx.strokeStyle = '#3a4a50'; ctx.lineWidth = 1; const centerX = width / 2, centerY = height * .53, step = Math.max(22, 32 * state.zoom); for (let x = centerX % step; x < width; x += step) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, height); ctx.stroke(); } for (let y = centerY % step; y < height; y += step) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(width, y); ctx.stroke(); } ctx.globalAlpha = .55; ctx.strokeStyle = '#52666b'; ctx.beginPath(); ctx.moveTo(0, centerY); ctx.lineTo(width, centerY); ctx.stroke(); ctx.restore(); }
function drawMesh() { const rect = canvas.getBoundingClientRect(), width = rect.width, height = rect.height, cx = width / 2, cy = height * .52, mesh = buildMesh(), maxExtent = Math.max(...mesh.vertices.map((v) => Math.abs(v[0]) + Math.abs(v[1]) + Math.abs(v[2])), 1), scale = Math.min(width, height) * .34 / maxExtent * state.zoom, projected = mesh.vertices.map((v) => project(v, scale, cx, cy)), sorted = mesh.triangles.map((tri) => ({ tri, depth: (projected[tri[0]].depth + projected[tri[1]].depth + projected[tri[2]].depth) / 3 })).sort((a, b) => a.depth - b.depth), part = currentPart(); ctx.save(); for (const item of sorted) { const [a, b, c] = item.tri.map((index) => projected[index]); const light = Math.max(.16, Math.min(.72, .38 + item.depth / 1400)); ctx.beginPath(); ctx.moveTo(a.x, a.y); ctx.lineTo(b.x, b.y); ctx.lineTo(c.x, c.y); ctx.closePath(); ctx.fillStyle = state.view === 'wire' ? 'transparent' : state.view === 'xray' ? `rgba(159,185,220,${light * .5})` : `rgba(229,222,210,${light})`; ctx.fill(); ctx.strokeStyle = part.color; ctx.globalAlpha = state.view === 'wire' ? .62 : .15; ctx.lineWidth = state.view === 'wire' ? 1 : .45; ctx.stroke(); } ctx.globalAlpha = 1; if (state.symmetry) { ctx.strokeStyle = 'rgba(149,211,160,.62)'; ctx.setLineDash([3, 5]); ctx.beginPath(); ctx.moveTo(cx, cy - height * .36); ctx.lineTo(cx, cy + height * .36); ctx.stroke(); ctx.setLineDash([]); } if (state.plane) { ctx.strokeStyle = 'rgba(159,185,220,.32)'; ctx.beginPath(); ctx.ellipse(cx, cy, Math.min(width, height) * .27 * state.zoom, Math.min(width, height) * .1 * state.zoom, -.1, 0, Math.PI * 2); ctx.stroke(); } ctx.restore(); }
function drawViewport() { const rect = canvas.getBoundingClientRect(); if (!rect.width || !rect.height) return; canvas.width = Math.round(rect.width * devicePixelRatio); canvas.height = Math.round(rect.height * devicePixelRatio); ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); ctx.fillStyle = '#101a21'; ctx.fillRect(0, 0, rect.width, rect.height); drawGrid(rect.width, rect.height); const glow = ctx.createRadialGradient(rect.width / 2, rect.height * .5, 15, rect.width / 2, rect.height * .5, Math.min(rect.width, rect.height) * .48); glow.addColorStop(0, 'rgba(149,211,160,.08)'); glow.addColorStop(1, 'rgba(149,211,160,0)'); ctx.fillStyle = glow; ctx.fillRect(0, 0, rect.width, rect.height); drawMesh(); }
function resizeCanvas() { requestAnimationFrame(drawViewport); }

function minimumWallForProcess() { if (state.process === 'Powder-bed fusion') return 1.5; if (state.process === '5-axis milling') return 2; if (state.process === 'SLA / DLP') return 1.2; return 2.5; }
function validateGeometry() { const mesh = buildMesh(), part = currentPart(), minimumWall = minimumWallForProcess(), computed = validateMeshCore(mesh, state.length, part.range, state.thickness, minimumWall), checks = [{ id: 'topology', label: 'Closed surface topology', detail: `${mesh.vertices.length} vertices · ${mesh.triangles.length} triangles`, status: computed.closed ? 'pass' : 'fail' }, { id: 'finite', label: 'Finite coordinates', detail: 'No NaN or infinite vertices', status: computed.finite ? 'pass' : 'fail' }, { id: 'envelope', label: 'Starter design envelope', detail: `${part.range[0]}–${part.range[1]} mm length`, status: computed.inRange ? 'pass' : 'fail' }, { id: 'wall', label: 'Process minimum wall', detail: `${state.thickness.toFixed(1)} mm vs ${minimumWall.toFixed(1)} mm minimum`, status: computed.wall ? 'pass' : 'fail' }, { id: 'source', label: 'Source / design intent', detail: sourceLabel(), status: 'review' }]; return { mesh, checks, pass: checks.every((check) => check.status !== 'fail'), review: checks.some((check) => check.status === 'review') }; }
function renderValidation() { const result = state.validationRun ? validateGeometry() : null, card = $('#validationCard'); if (!result) { card.className = 'validation-card is-neutral'; card.innerHTML = '<div class="validation-icon">•</div><div><strong>Not checked</strong><p>Run geometry checks before preparing export</p></div>'; $('#validationMessage').textContent = 'Run geometry checks before preparing export'; return; } const failed = result.checks.filter((check) => check.status === 'fail'); card.className = `validation-card ${failed.length ? 'is-fail' : 'is-review'}`; card.innerHTML = `<div class="validation-icon">!</div><div><strong>${failed.length ? `${failed.length} check${failed.length > 1 ? 's' : ''} blocked` : 'Geometry checks complete'}</strong><p>${failed.length ? failed[0].detail : 'Topology and envelope computed · clinical review still required'}</p></div>`; $('#validationMessage').textContent = failed.length ? 'Geometry blocked · resolve checks before preview' : 'Geometry computed · reviewer sign-off still required'; $('#workflowStatusIcon').textContent = '!'; $('#workflowStatusIcon').classList.remove('is-neutral'); $('#workflowStatusIcon').classList.add('is-review'); }
function renderWorkflow() { const steps = $$('#workflowSteps .step'), activeIndex = state.validationRun ? 3 : state.source.kind === 'imported' ? 1 : 0; steps.forEach((step, index) => { step.classList.toggle('is-active', index === activeIndex); step.classList.toggle('is-done', index < activeIndex); }); }
function renderCatalog() { const sources = state.catalog.sources || []; $('#catalogList').innerHTML = sources.map((source) => `<article class="catalog-row"><div class="catalog-icon">${source.id === 'dicom' ? '◈' : source.id === 'monai-label' ? '✦' : '◫'}</div><div class="catalog-copy"><strong>${source.name}</strong><small>${source.kind} · ${source.role}</small><div class="catalog-tags">${source.supports.slice(0, 3).map((tag) => `<span>${tag}</span>`).join('')}</div></div><a class="catalog-link" href="${source.url}" target="_blank" rel="noreferrer" aria-label="Open ${source.name}">↗</a></article>`).join(''); }
async function loadCatalog() { try { const response = await fetch('data/library-catalog.json'); if (response.ok) state.catalog = await response.json(); } catch { /* fallback keeps the app usable offline */ } renderCatalog(); }

function orientedTriangles(mesh) { return orientedTrianglesCore(mesh); }
function meshText(format) { const result = validateGeometry(), verts = result.mesh.vertices, tris = orientedTriangles(result.mesh), part = currentPart(); if (format === 'obj') return ['# pro-esthetic preview export', `# ${part.name}`, `# source: ${sourceLabel()}`, '# clinical_fit: not_assessed', '# manufacturing_qualified: false', ...verts.map((v) => `v ${v.map((n) => n.toFixed(4)).join(' ')}`), ...tris.map(([a, b, c]) => `f ${a + 1} ${b + 1} ${c + 1}`), ''].join('\n'); const lines = [`solid PRO_ESTHETIC_PREVIEW_${part.id}`]; for (const [ia, ib, ic] of tris) { const a = verts[ia], b = verts[ib], c = verts[ic], u = [b[0] - a[0], b[1] - a[1], b[2] - a[2]], v = [c[0] - a[0], c[1] - a[1], c[2] - a[2]], n = [u[1] * v[2] - u[2] * v[1], u[2] * v[0] - u[0] * v[2], u[0] * v[1] - u[1] * v[0]], mag = Math.hypot(...n) || 1; lines.push(`facet normal ${n.map((value) => (value / mag).toFixed(6)).join(' ')}`, ' outer loop', `  vertex ${a.join(' ')}`, `  vertex ${b.join(' ')}`, `  vertex ${c.join(' ')}`, ' endloop', 'endfacet'); } lines.push('endsolid PRO_ESTHETIC_PREVIEW'); return lines.join('\n'); }
function download(name, body, type) { const url = URL.createObjectURL(new Blob([body], { type })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 500); }
function renderExportReview() { const result = validateGeometry(); $('#exportCheckList').innerHTML = result.checks.map((check) => `<div class="export-check ${check.status}"><span>${check.status === 'pass' ? '✓' : check.status === 'fail' ? '!' : '•'}</span><div><strong>${check.label}</strong><small>${check.detail}</small></div><em>${check.status === 'pass' ? 'pass' : check.status === 'fail' ? 'blocked' : 'review'}</em></div>`).join(''); $('#exportModelName').textContent = currentPart().name; $('#exportModelDetail').textContent = `${sourceLabel()} · ${result.mesh.vertices.length} vertices · preview only`; $('#exportGateText').textContent = result.pass ? 'Preview export is gated by acknowledgment' : 'Resolve blocked checks before download'; $('#confirmExport').disabled = !result.pass || !$('#exportAck').checked; }
function exportManifest(format, result) { return JSON.stringify({ schema: 'pro-esthetic.preview-export.v1', generatedAt: new Date().toISOString(), application: 'pro-esthetic', exportMode: 'preview_only', format, study: { name: $('#studyName').textContent, sourceStatus: state.source.status, sourceName: state.source.name || null, files: state.source.files }, design: { kit: currentPart().id, name: currentPart().name, lengthMm: state.length, wallThicknessMm: state.thickness, blendRadiusMm: state.radius, symmetry: state.symmetry, plane: state.plane }, manufacturingMetadata: { material: state.material, process: state.process, layer: state.layer, qualified: false }, mesh: { vertexCount: result.mesh.vertices.length, triangleCount: result.mesh.triangles.length, checks: result.checks }, clinicalFit: 'not_assessed', reviewerSignOff: 'required' }, null, 2); }
function openExport() { state.validationRun = true; renderProperties(); renderExportReview(); $('#exportAck').checked = false; $('#exportModal').showModal(); } function closeExport() { $('#exportModal').close(); } function confirmExport() { const format = $('#exportFormat').value, result = validateGeometry(); if (!result.pass || !$('#exportAck').checked) return; download(`pro-esthetic-${currentPart().id}-PREVIEW.${format}`, meshText(format), 'text/plain'); download(`pro-esthetic-${currentPart().id}-PREVIEW.manifest.json`, exportManifest(format, result), 'application/json'); closeExport(); toast(`Preview ${format.toUpperCase()} + manifest downloaded · review before manufacture`); }
function handleSourceFiles(files) { if (!files.length) return; const allowed = /\.(dcm|nii|nii\.gz|json|png|jpe?g|webp)$/i, invalid = files.find((file) => file.size > 25 * 1024 * 1024 || !allowed.test(file.name)); if (invalid) { toast(`Source rejected · ${invalid.name} is unsupported or over 25 MB`); return; } state.source = { kind: 'imported', name: files.length === 1 ? files[0].name : `${files[0].name} + ${files.length - 1} more`, status: 'unverified-local', modality: null, voxelSpacing: null, orientation: null, frameOfReference: null, deidentification: 'unknown', segmentation: 'none', reviewerStatus: 'not_started', files: files.map((file) => ({ name: file.name, size: file.size, type: file.type })) }; state.validationRun = false; commitHistory(); renderProperties(); toast('Source queued locally · parsing and segmentation are not implemented'); }

$$('.rail-button[data-tool]').forEach((button) => button.addEventListener('click', () => { if (button.disabled) return; $$('.rail-button[data-tool]').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); state.tool = button.dataset.tool; $('#toolLabel').textContent = `${button.dataset.tool.toUpperCase()} / OBJECT`; if (state.tool === 'reference') openAtlas(); if (state.tool === 'measure') toast(`Bounds: ${state.length.toFixed(1)} mm along study axis`); if (state.tool === 'mirror') { state.symmetry = !state.symmetry; renderProperties(); drawViewport(); toast(`Symmetry ${state.symmetry ? 'enabled' : 'disabled'}`); } }));
$$('.filter-chip').forEach((button) => button.addEventListener('click', () => { $$('.filter-chip').forEach((item) => { item.classList.remove('is-active'); item.setAttribute('aria-selected', 'false'); }); button.classList.add('is-active'); button.setAttribute('aria-selected', 'true'); state.category = button.dataset.category; renderLibrary(); }));
$$('.view-mode').forEach((button) => button.addEventListener('click', () => { $$('.view-mode').forEach((item) => item.classList.remove('is-active')); button.classList.add('is-active'); state.view = button.dataset.view; drawViewport(); }));
$('#librarySearch').addEventListener('input', (event) => { state.query = event.target.value; renderLibrary(); });
[['#lengthSlider', 'length', '#lengthOutput', ' mm'], ['#thicknessSlider', 'thickness', '#thicknessOutput', ' mm'], ['#radiusSlider', 'radius', '#radiusOutput', ' mm']].forEach(([selector, key, output, suffix]) => { $(selector).addEventListener('input', (event) => { state[key] = Number(event.target.value); $(output).textContent = `${state[key].toFixed(1)}${suffix}`; if (key === 'length') $('#measureValue').textContent = state[key].toFixed(1); state.validationRun = false; renderValidation(); drawViewport(); }); $(selector).addEventListener('change', () => commitHistory()); });
['#materialSelect', '#processSelect', '#layerSelect'].forEach((selector) => $(selector).addEventListener('change', (event) => { const key = selector === '#materialSelect' ? 'material' : selector === '#processSelect' ? 'process' : 'layer'; state[key] = event.target.value; state.validationRun = false; commitHistory(); renderProperties(); drawViewport(); }));
['#symmetryToggle', '#planeToggle'].forEach((selector) => $(selector).addEventListener('click', () => { const key = selector.includes('symmetry') ? 'symmetry' : 'plane'; state[key] = !state[key]; state.validationRun = false; commitHistory(); renderProperties(); drawViewport(); }));
$('#resetGeometry').addEventListener('click', () => { const part = currentPart(); state.length = part.length; state.thickness = part.thickness; state.radius = part.radius; state.validationRun = false; commitHistory(); renderProperties(); drawViewport(); toast('Geometry reset to template values'); }); $('#gridButton').addEventListener('click', () => { state.grid = !state.grid; drawViewport(); toast(state.grid ? 'Construction grid shown' : 'Construction grid hidden'); }); $('#fitButton').addEventListener('click', () => { state.zoom = 1; state.yaw = -.32; state.pitch = -.1; drawViewport(); toast('Viewport fitted to current mesh'); });
$('#viewport').addEventListener('pointerdown', (event) => { state.dragging = true; state.lastX = event.clientX; state.lastY = event.clientY; $('#viewport').setPointerCapture(event.pointerId); }); $('#viewport').addEventListener('pointermove', (event) => { if (!state.dragging) return; state.yaw += (event.clientX - state.lastX) * .008; state.pitch = Math.max(-.8, Math.min(.8, state.pitch + (event.clientY - state.lastY) * .006)); state.lastX = event.clientX; state.lastY = event.clientY; drawViewport(); }); $('#viewport').addEventListener('pointerup', () => { state.dragging = false; }); $('#viewport').addEventListener('wheel', (event) => { event.preventDefault(); state.zoom = Math.max(.6, Math.min(1.7, state.zoom - event.deltaY * .001)); drawViewport(); }, { passive: false }); $('#viewport').addEventListener('keydown', (event) => { if (event.key.toLowerCase() === 'r') { state.zoom = 1; state.yaw = -.32; state.pitch = -.1; drawViewport(); } });
$('#saveButton').addEventListener('click', () => { localStorage.setItem('pro-esthetic-snapshot-v2', snapshot()); toast('Snapshot saved locally · reload can restore it'); }); $('#validateButton').addEventListener('click', () => { state.validationRun = true; renderProperties(); renderExportReview(); toast('Geometry checks computed'); }); $('#exportButton').addEventListener('click', openExport); $('#exportStlButton').addEventListener('click', openExport);
$('#undoButton').addEventListener('click', () => { if (state.historyIndex <= 0) return toast('No earlier state in this study'); state.historyIndex -= 1; Object.assign(state, JSON.parse(state.history[state.historyIndex])); renderLibrary(); renderProperties(); drawViewport(); toast('Previous study state restored'); }); $('#redoButton').addEventListener('click', () => { if (state.historyIndex >= state.history.length - 1) return toast('No later state in this study'); state.historyIndex += 1; Object.assign(state, JSON.parse(state.history[state.historyIndex])); renderLibrary(); renderProperties(); drawViewport(); toast('Next study state restored'); });
function openAtlas() { renderCatalog(); $('#atlasModal').showModal(); } function closeAtlas() { $('#atlasModal').close(); } function openHelp() { $('#helpModal').showModal(); }
$('#referenceAtlasButton').addEventListener('click', openAtlas); $('#closeAtlas').addEventListener('click', closeAtlas); $('#helpButton').addEventListener('click', openHelp); $('#closeHelp').addEventListener('click', () => $('#helpModal').close()); $('#importReferenceButton').addEventListener('click', () => $('#referenceInput').click()); $('#referenceInput').addEventListener('change', (event) => handleSourceFiles([...event.target.files])); $('#importStudyButton').addEventListener('click', () => $('#studyInput').click()); $('#studyCardAction').addEventListener('click', () => $('#studyInput').click()); $('#studyInput').addEventListener('change', (event) => handleSourceFiles([...event.target.files])); $('#addPartButton').addEventListener('click', () => selectPart('blank')); $('#menuButton').addEventListener('click', openHelp); $('#inspectorButton').addEventListener('click', () => { const panel = $('#propertiesPanel'); const isOpen = panel.classList.toggle('is-open'); $('#inspectorButton').setAttribute('aria-expanded', isOpen); }); $('#cameraButton').addEventListener('click', () => { const link = document.createElement('a'); link.href = canvas.toDataURL('image/png'); link.download = 'pro-esthetic-viewport.png'; link.click(); toast('Viewport image captured'); }); $('#closeExport').addEventListener('click', closeExport); $('#exportAck').addEventListener('change', renderExportReview); $('#confirmExport').addEventListener('click', confirmExport);
document.addEventListener('keydown', (event) => { if (event.key === '/' && document.activeElement.tagName !== 'INPUT') { event.preventDefault(); $('#librarySearch').focus(); } if (event.key === 'Escape') { if ($('#atlasModal').open) closeAtlas(); if ($('#helpModal').open) $('#helpModal').close(); if ($('#exportModal').open) closeExport(); } }); window.addEventListener('resize', resizeCanvas);

try { const saved = localStorage.getItem('pro-esthetic-snapshot-v2'); if (saved) Object.assign(state, JSON.parse(saved)); } catch { /* a fresh study is safer than a partial snapshot */ }
commitHistory(); renderLibrary(); renderProperties(); loadCatalog(); resizeCanvas();
